server {
    listen 80;
    listen [::]:80;
    server_name ordprov.com www.ordprov.com;

    # Global redirect to HTTPS
    return 301 https://$host$request_uri;
}

server {
    # listen 80;
    # listen [::]:80;
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ordprov.com www.ordprov.com;

    # ssl_certificate     cert.pem;
    # ssl_certificate_key privatekey.key;
    # /etc/letsencrypt/live/ordprov.com/fullchain.pem
    ssl_certificate     /etc/letsencrypt/live/ordprov.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ordprov.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    proxy_read_timeout 500;
    proxy_connect_timeout 500;
    proxy_send_timeout 500;

    root /usr/share/nginx/frontend/dist/;

    location /api {
      proxy_pass http://backend:3000/api;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Proto https;
    }

    # location /images {
    #   root /usr/share/nginx;
    #   add_header Cache-Control "public";
    #   expires 1M;
    # }
    
    location / {
      # alias /usr/share/nginx/frontend/dist/;
      try_files $uri $uri/ /index.html;

      # Disable caching for all .html files
      location ~ \.html$ {
          add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
      }
    }
  # Enable gzip compression
  gzip on;

  # Compression level (1-9). Higher is more compressed but takes more CPU.
  gzip_comp_level 6;

  # Types of files to compress
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

  # Disable gzip for IE6 as it may cause issues
  gzip_disable "msie6";

  # Minimum file size to compress (in bytes)
  gzip_min_length 1024;

  # Buffer size for gzip
  gzip_buffers 16 8k;

  # Use HTTP version 1.1 for gzip
  gzip_http_version 1.1;

  # Compress files even if a client doesn't request it
  gzip_vary on;
}
